# Generated by Django 4.1.1 on 2022-09-18 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeDeransaction', models.BooleanField(choices=[('VENTE', 'vente'), ('DEMANDE', 'Demande')])),
                ('ville', models.CharField(max_length=200)),
                ('secteur', models.CharField(max_length=200)),
                ('etat', models.CharField(choices=[('NEUF', 'Neuf'), ('TRESBON', 'Très bon'), ('BON', 'Bon'), ('ENDOMMAGE', 'Endommagé')], max_length=200)),
                ('titreAnnonce', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=20)),
                ('photo', models.ImageField(upload_to='')),
                ('dateAnnonce', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ATO',
            fields=[
                ('annonce_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='annonces.annonce')),
                ('model', models.CharField(max_length=200)),
                ('marque', models.CharField(max_length=200)),
            ],
            bases=('annonces.annonce',),
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='annonces.category')),
            ],
        ),
    ]
