# Generated by Django 4.1.1 on 2022-09-19 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annonce',
            old_name='subCategory',
            new_name='subcategories',
        ),
        migrations.RemoveField(
            model_name='annonce',
            name='typeDeransaction',
        ),
        migrations.AddField(
            model_name='annonce',
            name='typeDeTransaction',
            field=models.CharField(choices=[('VENTE', 'vente'), ('DEMANDE', 'Demande')], default='VENTE', max_length=200),
        ),
    ]
