# Generated by Django 4.1.1 on 2022-09-19 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0003_rename_subcategory_annonce_subcategories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='dateAnnonce',
            field=models.DateField(auto_now_add=True),
        ),
    ]
