# Generated by Django 4.1.1 on 2022-09-19 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('annonces', '0004_alter_annonce_dateannonce'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='annonceUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annonces', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='subcategories',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annonces', to='annonces.subcategory'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='categories',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='annonces.category'),
        ),
    ]
