# Generated by Django 4.1.1 on 2022-09-24 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0005_alter_annonce_annonceuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='prix',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20),
        ),
    ]
